spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 454059752980-bgal34ffrvj9nj56d6e8ac59voq1r4iu.apps.googleusercontent.com
            client-secret: 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