version: "3.9"
services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_DB=kernel_panic'
  kernel-panic:
    depends_on:
      - postgres
    build:
      context: docker
      dockerfile: Dockerfile
    image: kernel_panic_back
    restart: always
    ports:
      - "8080:8080"
    environment:
      - 'DB_URL=jdbc:postgresql://postgres:5432/kernel_panic'
      - 'DB_USER=postgres'
      - 'DB_PASSWORD=postgres'
      - 'JWT=0JvQrtCR0JvQriDQodCe0KHQkNCi0Kwg0JHQntCb0KzQqNCY0JUg0JLQntCb0J7QodCQ0KLQq9CVINCl0KPQmA=='
